# 只编译显式列出的实现；后续任务的空占位文件不纳入构建。
function(autoaim_module name)
  if(ARGN)
    add_library(autoaim_${name} STATIC ${ARGN})
    set(visibility PUBLIC)
  else()
    add_library(autoaim_${name} INTERFACE)
    set(visibility INTERFACE)
  endif()
  target_include_directories(autoaim_${name} ${visibility} ${PROJECT_SOURCE_DIR}/include)
  target_link_libraries(autoaim_${name} ${visibility} autoaim_options)
endfunction()

function(autoaim_dependencies name)
  set(allowed_math core)
  set(allowed_hal core)
  set(allowed_vision math)
  set(allowed_estimation vision)
  set(allowed_decision estimation)
  set(allowed_control hal)
  set(allowed_mission decision)
  set(allowed_pipeline mission control hal)
  get_target_property(kind autoaim_${name} TYPE)
  if(kind STREQUAL "INTERFACE_LIBRARY")
    set(visibility INTERFACE)
  else()
    set(visibility PUBLIC)
  endif()
  foreach(dependency IN LISTS ARGN)
    if(NOT dependency IN_LIST allowed_${name})
      message(FATAL_ERROR "Forbidden module dependency: ${name} -> ${dependency}")
    endif()
    target_link_libraries(autoaim_${name} ${visibility} autoaim_${dependency})
  endforeach()
endfunction()
