function(autoaim_test name source)
  add_executable(${name} ${source})
  target_include_directories(${name} PRIVATE tests)
  target_link_libraries(${name} PRIVATE autoaim_options ${ARGN})
  add_test(NAME ${name} COMMAND ${name})
  set_tests_properties(${name} PROPERTIES TIMEOUT 30)
endfunction()

if(BUILD_TESTING)
  find_package(Python3 REQUIRED COMPONENTS Interpreter)
  if(UNIX AND NOT APPLE)
    add_test(NAME test_install_script COMMAND ${Python3_EXECUTABLE}
      ${PROJECT_SOURCE_DIR}/tests/unit/test_install_script.py)
    set_tests_properties(test_install_script PROPERTIES TIMEOUT 30)
  endif()
  add_test(NAME module_boundaries COMMAND ${Python3_EXECUTABLE}
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/check_dependencies.py ${CMAKE_CURRENT_SOURCE_DIR})
  add_test(NAME boundary_checker_self_test COMMAND ${Python3_EXECUTABLE}
    ${CMAKE_CURRENT_SOURCE_DIR}/cmake/check_dependencies.py --self-test)
  autoaim_test(test_smoke tests/unit/test_smoke.cpp)
  autoaim_test(test_result tests/unit/test_result.cpp autoaim_core)
  autoaim_test(test_time tests/unit/test_time.cpp autoaim_core)
  autoaim_test(test_stamp tests/unit/test_stamp.cpp autoaim_core)
  autoaim_test(test_evidence tests/unit/test_evidence.cpp autoaim_core)
  autoaim_test(test_logging tests/unit/test_logging.cpp autoaim_core)
  autoaim_test(test_config tests/unit/test_config.cpp autoaim_core)
  autoaim_test(test_angle tests/unit/test_angle.cpp autoaim_math)
  autoaim_test(test_numeric tests/unit/test_numeric.cpp autoaim_math)
  autoaim_test(test_se3 tests/unit/test_se3.cpp autoaim_math)
  autoaim_test(test_transform tests/unit/test_transform.cpp autoaim_math)
  autoaim_test(test_data_contracts tests/contract/test_data_contracts.cpp autoaim_pipeline)
  autoaim_test(test_hal tests/unit/test_hal.cpp autoaim_hal)
  autoaim_test(test_frame_sync tests/contract/test_frame_sync.cpp autoaim_pipeline)
  autoaim_test(test_async_buffer_lifetime tests/contract/test_async_buffer_lifetime.cpp autoaim_core)
  autoaim_test(test_frame_queue tests/contract/test_frame_queue.cpp autoaim_pipeline)
  autoaim_test(test_out_of_order_completion tests/contract/test_out_of_order_completion.cpp autoaim_pipeline)
  autoaim_test(test_command_slot tests/contract/test_command_slot.cpp autoaim_pipeline)
  autoaim_test(test_worker_exception tests/contract/test_worker_exception.cpp autoaim_pipeline)
  autoaim_test(test_crc tests/unit/test_crc.cpp autoaim_control)
  autoaim_test(test_protocol tests/unit/test_protocol.cpp autoaim_control)
  autoaim_test(test_watchdog tests/unit/test_watchdog.cpp autoaim_control)
  autoaim_test(test_smoother tests/unit/test_smoother.cpp autoaim_control)
  autoaim_test(test_mode_switch_staleness tests/contract/test_mode_switch_staleness.cpp autoaim_control)
  autoaim_test(test_publish_failure_shutdown tests/contract/test_publish_failure_shutdown.cpp autoaim_control)
  autoaim_test(test_calibration tests/unit/test_calibration.cpp autoaim_vision)
  autoaim_test(test_traditional_detector tests/unit/test_traditional_detector.cpp autoaim_vision)
  autoaim_test(test_yolov5 tests/unit/test_yolov5.cpp autoaim_vision)
  autoaim_test(test_corner_semantics tests/unit/test_corner_semantics.cpp autoaim_vision)
  autoaim_test(test_corner_refine tests/unit/test_corner_refine.cpp autoaim_vision)
  autoaim_test(test_pnp tests/unit/test_pnp.cpp autoaim_vision)
  autoaim_test(test_pose_quality tests/unit/test_pose_quality.cpp autoaim_vision)
  autoaim_test(test_observation tests/unit/test_observation.cpp autoaim_estimation)
  autoaim_test(test_geometry tests/unit/test_geometry.cpp autoaim_estimation)
  autoaim_test(test_motion_model tests/unit/test_motion_model.cpp autoaim_estimation)
  autoaim_test(test_acceleration_model tests/unit/test_acceleration_model.cpp autoaim_estimation)
  autoaim_test(test_measurement_model tests/unit/test_measurement_model.cpp autoaim_estimation)
  autoaim_test(test_ekf tests/unit/test_ekf.cpp autoaim_estimation)
  autoaim_test(test_health tests/unit/test_health.cpp autoaim_estimation)
  autoaim_test(test_association tests/unit/test_association.cpp autoaim_estimation)
  autoaim_test(test_armor_id_synthetic tests/synthetic/test_armor_id_synthetic.cpp autoaim_estimation)
  autoaim_test(test_geometry_selector_synthetic tests/synthetic/test_geometry_selector_synthetic.cpp autoaim_estimation)
  autoaim_test(test_state_machine tests/unit/test_state_machine.cpp autoaim_estimation)
  autoaim_test(test_motion_selection tests/unit/test_motion_selection.cpp autoaim_estimation)
  autoaim_test(test_tracker tests/synthetic/test_tracker.cpp autoaim_estimation)
  autoaim_test(test_tracker_set tests/synthetic/test_tracker_set.cpp autoaim_estimation)
  autoaim_test(test_predictor tests/unit/test_predictor.cpp autoaim_decision)
  autoaim_test(test_ballistic tests/unit/test_ballistic.cpp autoaim_decision)
  autoaim_test(test_intercept tests/unit/test_intercept.cpp autoaim_decision)
  autoaim_test(test_armor_selector tests/unit/test_armor_selector.cpp autoaim_decision)
  autoaim_test(test_aim_adequacy tests/unit/test_aim_adequacy.cpp autoaim_decision)
  autoaim_test(test_mission_factory tests/unit/test_mission_factory.cpp autoaim_mission)
  autoaim_test(test_target_selector tests/unit/test_target_selector.cpp autoaim_mission)
  autoaim_test(test_infantry_assist tests/unit/test_infantry_assist.cpp autoaim_mission)
  autoaim_test(test_manual_takeover tests/contract/test_manual_takeover.cpp autoaim_mission)
  autoaim_test(test_sentry_mission tests/unit/test_sentry_mission.cpp autoaim_mission)
  autoaim_test(test_file_replay tests/unit/test_file_replay.cpp autoaim_hal)
  autoaim_test(test_recording_transport tests/unit/test_recording_transport.cpp autoaim_hal)
  autoaim_test(test_serial_disconnected tests/unit/test_serial_disconnected.cpp autoaim_hal)
  autoaim_test(test_can_disconnected tests/unit/test_can_disconnected.cpp autoaim_hal)
  autoaim_test(test_camera_disconnected tests/unit/test_camera_disconnected.cpp autoaim_hal)
  autoaim_test(test_bootstrap tests/unit/test_bootstrap.cpp autoaim_pipeline)
  autoaim_test(test_replay_publisher tests/contract/test_replay_publisher.cpp autoaim_control)
  autoaim_test(test_pipeline_lifecycle tests/contract/test_pipeline_lifecycle.cpp autoaim_pipeline)
  autoaim_test(test_pipeline_chain tests/contract/test_pipeline_chain.cpp autoaim_pipeline)
  autoaim_test(test_pipeline_mode_exit tests/contract/test_pipeline_mode_exit.cpp autoaim_pipeline)
  autoaim_test(test_file_pipeline tests/contract/test_file_pipeline.cpp autoaim_pipeline)
  add_test(NAME test_entry_help COMMAND autoaim_node --help)
  add_test(NAME test_synthetic_tool COMMAND synthetic_sim --config ${PROJECT_SOURCE_DIR}/config/offline/armor.yaml --self-test)
  add_test(NAME test_protocol_tool COMMAND protocol_tester --self-test)
  add_test(NAME test_calibration_tool COMMAND calibration_tool --config ${PROJECT_SOURCE_DIR}/config/offline/armor.yaml --self-test)
  add_test(NAME test_detector_benchmark COMMAND bench_detector --config ${PROJECT_SOURCE_DIR}/config/offline/armor.yaml --self-test)
  add_test(NAME test_visualizer_help COMMAND replay_visualizer --help)
  add_test(NAME test_metrics_tool COMMAND pipeline_metrics --self-test)
  add_test(NAME test_live_disabled COMMAND autoaim_node --config ${PROJECT_SOURCE_DIR}/config/hardware/disabled.yaml)
  set_tests_properties(test_live_disabled PROPERTIES WILL_FAIL TRUE TIMEOUT 5)
  autoaim_test(test_hit_probability_synthetic tests/synthetic/test_hit_probability_synthetic.cpp autoaim_decision)
  set(AUTOAIM_TEST_YOLOV5_MODEL "" CACHE FILEPATH "Optional explicit model path for offline inference smoke test")
  if(AUTOAIM_OPENVINO AND AUTOAIM_TEST_YOLOV5_MODEL)
    add_test(NAME test_openvino_model COMMAND test_yolov5 "${AUTOAIM_TEST_YOLOV5_MODEL}")
    set_tests_properties(test_openvino_model PROPERTIES TIMEOUT 60)
    add_executable(test_openvino_async tests/contract/test_openvino_async.cpp)
    target_include_directories(test_openvino_async PRIVATE tests)
    target_link_libraries(test_openvino_async PRIVATE autoaim_vision)
    add_test(NAME test_openvino_async COMMAND test_openvino_async "${AUTOAIM_TEST_YOLOV5_MODEL}")
    set_tests_properties(test_openvino_async PROPERTIES TIMEOUT 60)
    add_executable(test_pipeline_async tests/contract/test_pipeline_async.cpp)
    target_include_directories(test_pipeline_async PRIVATE tests)
    target_link_libraries(test_pipeline_async PRIVATE autoaim_pipeline)
    add_test(NAME test_pipeline_async COMMAND test_pipeline_async "${AUTOAIM_TEST_YOLOV5_MODEL}")
    set_tests_properties(test_pipeline_async PROPERTIES TIMEOUT 60)
  endif()
  add_test(NAME test_check_failure COMMAND test_smoke --fail)
  set_tests_properties(test_check_failure PROPERTIES WILL_FAIL TRUE TIMEOUT 5)
endif()
